
services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    #ports:
    #  - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']


  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    ports:
      - 8080:8081
    restart: always


  poke-app:
    container_name: ${POKE_APP_NAME}
    image: klerith/pokemon-nest-app:1.0.0
    depends_on:
      - db
      - mongo-express
    ports:
      - 3000:3000

    environment:
      MONGODB: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:27017
      DB_NAME: poke_db
    restart: always

  
volumes:
  poke-vol:
    external: false


